### PR TITLE
Migrate the portainer executor over to a self-contained pex file

### PR DESCRIPTION
**Pull request by tarnfeld**
Thanks @orls for implementing!

### CODE REVIEW

**Comment by tarnfeld** [comment]
Would you mind updating the executor section of the [readme](https://github.com/duedil-ltd/portainer#1-upload-the-mesos-executor) to talk more about PEX?

**Comment by orls** [comment]
Done; let me know your thoughts.

**Comment by orls** [comment]
One thing that's maybe worth mentioning (but I didn't want to clutter the readme any more, it's getting rather long!):

Because of the way our 'traditional', un-pexed bin-scripts work, it _is_ still possible to do things the old way and just use a zip of the raw source. The runtime invoke (made by the scheduler) is the same, `bin/portainer build-executor` (*), meaning that the pex is _just_ a faster route to getting dependencies and python package faff out of the way. Functionally, they're identical.

(This is rather neat, and is a validation both of our `bin/setup` / virtualenv approach and of pex itself!)

----

* -- as an aside, that's such a troll command name -- it's confusing and janky having `bin/portainer build-executor`, with "build" being a noun ("the executor for the build"),  and also having the util script `bin/build-executor` with "build" as a verb ("build the executor"). Gah.

**Comment by tarnfeld** [comment]
:+1: :shipit: 

Nice!

**Pull request merged**
